export const GET_INBOX_ADVICE = "GET_INBOX_ADVICE"
export const GET_ADVICE = "GET_ADVICE"

export const SUBMIT_INBOX_ADVICE = "SUBMIT_INBOX_ADVICE"
export const SUBMIT_ADVICE = "SUBMIT_ADVICE"
export const SUBMIT_CATEGORY = "SUBMIT_CATEGORY"
export const SUBMIT_SUBCATEGORY = "SUBMIT_SUBCATEGORY"

export const DELETE_INBOX_ADVICE = "DELETE_INBOX_ADVICE"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY"
export const DELETE_ADVICE = "DELETE_ADVICE"

export const UPDATE_ADVICE = "UPDATE_ADVICE"
export const MOVE_INBOX_ADVICE = "MOVE_INBOX_ADVICE"