language: node_js
cache: npm
node_js:
    - "12"

addons:
    ssh_known_hosts: advicetracker.life

before_install:
    - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
      -in travis_rsa.enc -out travis_rsa -d
    - chmod 600 travis_rsa
    - mv travis_rsa ~/.ssh/id_rsa

services:
    - docker

install:
    - npm ci && cd app && npm ci && cd .. && cd server && npm ci

script:
    - cd .. && npm test
    
deploy:
    provider: script
    script: bash deploy.sh
    on:
        branch: master
