language: node_js
cache: npm
node_js:
- '12'
services:
- docker
install:
- npm ci && cd app && npm ci && cd .. && cd server && npm ci
script:
- cd .. && npm test
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master