version: "3.7"

services:
    client:
        container_name: client
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        env_file: ./app/.env
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true # react-scripts bug ?
        depends_on:
            - server
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        env_file: ./server/.env
        environment:
            - NODE_ENV=production
            - PORT=8080
        depends_on:
            - db
    db:
        container_name: db
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
