# pull official base image
FROM node:13.13.0-alpine as build

# set working directory
WORKDIR /app

# install app dependencies
COPY package*.json /app/

RUN npm install

# add app
COPY ./ /app/

RUN npm run build

FROM nginx:1.17.10-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3030

# start app
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]